language: python
python:
  - '2.7'
install: 
  - pip install -r requirements.txt
  - pip install coveralls codecov
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE ireporter;" -U postgres
  - psql -c "CREATE DATABASE test_ireporter;" -U postgres  
  - psql -c "CREATE USER raywire WITH PASSWORD 'raywire2018';" -U postgres
  - psql -c "grant all privileges on database ireporter to raywire ;" -U postgres
  - psql -c "grant all privileges on database test_ireporter to raywire ;" -U postgres 
script: 
  - pytest --cov-report term-missing --cov=./app
after_success:
  - coveralls
  - codecov --token=ciZnYrHGTEOUqiHSFZbotto9JdM8QSJb
cache: pip
